global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9009']
  - job_name: 'node_exporter_ubuntu'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'mysqld_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9104']
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx] 
    static_configs:
      - targets:
        - http://wp.local 
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: ['127.0.0.1:9115']
  - job_name: 'php-fpm'
    static_configs:
      - targets: ['127.0.0.1:9253']
  - job_name: 'nginx'
    static_configs:
      - targets: ['127.0.0.1:9113']

rule_files:
  - alert.rules_node.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

remote_write:
  - url: http://localhost:9009/api/v1/push
    write_relabel_configs:
      - target_label: site
        replacement: prod
